#!/usr/bin/env bash
# Setup minimalKioskOS
# Install Chromium and disable SSH
# Written by Sylvia van Os
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

set +x

apt-get update
# Install Chromium
apt-get install -y rpi-chromium-mods

# Install Python dep
apt-get install -y python3-pip
pip3 install pychrome --break-system-packages

# Disable SSH
rm -f /boot/ssh

# Auto-hide mouse support
apt-get install -y unclutter

# Install xdotool
apt-get install -y xdotool

set -x

cat <<EOF > /etc/systemd/system/firstboot.service
[Unit]
Description=First Boot Script
After=network.target

[Service]
Type=oneshot
ExecStart=/root/bin/firstboot.sh
ExecStartPost=/bin/rm -f /etc/systemd/system/firstboot.service
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl enable firstboot.service

# Unpack root at the end, so files are modified before
unpack /filesystem/root /
