services:
  custompios:
    image: ghcr.io/guysoft/custompios:devel
    container_name: mydistro_builder
    tty: true
    restart: always
    privileged: true
    volumes:
      - ./:/distro
    devices:
      - /dev/loop-control
