name: Build CustomPiOS Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free up disk space
      uses: insightsengineering/disk-space-reclaimer@v1
      with:
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        swap-storage: true
        docker-images: true
        tools-cache: false

    - name: Check disk space
      run: df -h
    - name: Update apt
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt install coreutils p7zip-full qemu-user-static python3-git
    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS
    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        path: repository
        submodules: true
    - name: Check cache for base image
      id: cache-base
      uses: actions/cache@v4
      with:
        path: repository/src/image/base.img.zip
        key: base-image-${{ hashFiles('repository/src/modules/fullpageos/**') }}

    - name: Download Raspbian Image
      if: steps.cache-base.outputs.cache-hit != 'true'
      run: |
        mkdir -p repository/src/image
        cd repository/src/image
        wget -q -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf_latest'

    - name: Build Base Image (if not cached)
      if: steps.cache-base.outputs.cache-hit != 'true'
      run: |
        cd repository/src
        ../../CustomPiOS/src/update-custompios-paths
        sudo modprobe loop
        sudo MODULES="base(network,gui(fullpageos))" bash -x ./build_dist
        cp workspace/*-raspios-*-lite.img image/base.img
        cd image
        zip base.img.zip base.img
        rm base.img

    # - name: Build Final Image (application layer)
    #   run: |
    #     rm -rf repository/src/workspace  # Clean previous build artifacts
    #     cd repository/src
    #     sudo modprobe loop
    #     sudo MODULES="myapp" BASE_ZIP_IMG="image/base.img.zip" bash -x ./build_dist
    #     cp workspace/*-raspios-*-lite.img ../image/final.img
    #     cd ../image
    #     zip final.zip final.img
    #     rm final.img

    # - name: Upload Final Image Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: final.img.zip
    #     path: repository/src/image/final.img.zip
